### ISSUE TITLE
Please add line break to Traffic Splitting Guide

### ISSUE THREAD

**Issue by Steve-O-Murphy** [edgio-docs/edgio-docs#553]
In https://docs.layer0.co/guides/traffic_splitting, "Step 3. Configure Traffic Splitting Rules in the Edgio Developer Console" has a sub step 3.b that needs to be on a new line.  Please see attachment.
![traffic-splitting](https://user-images.githubusercontent.com/30219968/199776692-2f5fc08a-5934-4794-a870-cfdf1c316c4e.png)

PS, the docs site looks amazing. 

Thank you.

**Comment by BhaswatiRoy** [comment]
Hello @Steve-O-Murphy 
We can add a <br> tag between both lines to solve the prob 
I can work on this!
![image](https://user-images.githubusercontent.com/78029145/212549990-946d9523-eaf6-416c-ba0c-f47fb7478af4.png)
